### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by remembertoremind** [jwoglom/signal-curses#10]
Hi. I cloned your repo and followed the instructions in the readme. This what i got:

```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    import pydbus
  File "/usr/lib/python3.7/site-packages/pydbus/__init__.py", line 1, in <module>
    from .bus import SystemBus, SessionBus, connect
  File "/usr/lib/python3.7/site-packages/pydbus/bus.py", line 1, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi.repository'
```

There is a good chance it's a user error ;)

**Comment by jwoglom** [comment]
Hi! In order for signal-curses to start correctly, you must have pygobject installed. Try following the instructions here: https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python
