### ISSUE TITLE
signal.run() fails

### ISSUE THREAD

**Issue by RaghavRao** [jwoglom/signal-curses#19]
Here is the traceback:
```

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    scurses.launcher.run(args)
  File "/home/raghav/Development/signal-curses/scurses/launcher/__init__.py", line 30, in run
    signal.run()
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/apNPSApplicationManaged.py", line 148, in main
    self.onStart()
  File "/home/raghav/Development/signal-curses/scurses/__init__.py", line 300, in onStart
    self.addForm('MAIN', SelectForm, name='Select User/Group')
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/apNPSApplicationManaged.py", line 55, in addForm
    fm = FormClass( parentApp=self, *args, **keywords)
  File "/home/raghav/Envs/signal-curses/lib/python3.7/site-packages/npyscreen/fmForm.py", line 70, in __init__
    self.create()
  File "/home/raghav/Development/signal-curses/scurses/__init__.py", line 171, in create
    g['name'], ', '.join(g['members'])))
TypeError: sequence item 0: expected str instance, dict found

```
I am on python 3.7.6 on fedora 31.

This is my pip freeze:

```

greenlet==0.4.15
msgpack==1.0.0
neovim==0.3.1
npyscreen==4.10.5
pydbus==0.6.0
pynvim==0.4.1
PyQRCode==1.2.1
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
vext==0.7.3
vext.gi==0.7.0

```

**Comment by elsehow** [comment]
Experiencing the same issue on Ubuntu 18

**Comment by elsehow** [comment]
@RaghavRao I was able to solve this issue (at least temporarily) by clearing the signal-cli config, running `rm -rf ~/local/share/signal-cli/*`

**Comment by jwoglom** [comment]
This has to do with some changes in how signal-cli represents contact and group data on disk. Hoping to do some refactoring work in signal-curses to better handle these issues soon.

**Comment by elsehow** [comment]
@jwoglom Feel free to let me know if you want a hand.
